---
instance_name: spot
monitoring:
  prometheus_node_exporter:
    enabled: false
    externally_accessible: false
  grafana:
    enabled: false
    externally_accessible: true
    admin_user: pgspotops
    admin_password: "{{ instance_name }}"
    anonymous_access: true
    protocol: https
