apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pg-spot-operator.fullname" . }}
  labels:
    {{- include "pg-spot-operator.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "pg-spot-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pg-spot-operator.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pg-spot-operator.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            - name: ssh-data
              mountPath: /app/.ssh
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        - name: ssh-data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "pg-spot-operator.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- end }}
