{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "pg-spot-operator.fullname" . }}-pv
  labels:
    {{- include "pg-spot-operator.labels" . | nindent 4 }}
spec:
  capacity:
    storage: {{ .Values.persistence.size | quote }}
  accessModes:
    - {{ .Values.persistence.accessMode | quote }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  # Define your storage backend here (e.g., hostPath, nfs, etc.)
  hostPath:
    path: /data/{{ include "pg-spot-operator.fullname" . }}-pv
{{- end }}
