# User provided manifest as provided
---
instance_manifest:
  api_version: v1
  kind: pg_spot_operator_instance
  cloud: aws
  region: eu-north-1
  instance_name: hello-aws
  #expiration_date: now
  postgresql:
    version: 16
    admin_user: admin
    admin_user_password: seitselehma
    config_lines:
      - "cluster_name = {{ postgres_cluster_name }}"
      - "statement_timeout = '5min'"
      - "shared_preload_libraries = 'auth_delay'"
      - "auth_delay.milliseconds = '5000'"
      - "archive_mode = on"
      - "archive_command = '/bin/true'"
      - "listen_addresses = '*'"
      - "logging_collector = on"
      - "log_filename = 'postgresql-%a.log'"
      - "log_truncate_on_rotation = on"
  backup:  # Only supported backup tool is pgBackRest currently
    type: none  # none | pgbackrest
    s3_bucket: pg-spot-ops-dev
    pgbackrest:
      global_settings:
        repo1-s3-region: eu-north-1
        repo1-s3-endpoint: s3.eu-north-1.amazonaws.com
  vm:
    cpu_min: 4
  os:
    extra_packages: [pgbadger]
    ssh_pub_key_paths:
      - ~/.ssh/google_compute_engine.pub
  user_tags:
    app: shop
