---

uuid: "{{ instance_manifest.uuid | d(engine_overrides.uuid) | d(None)}}"
api_version: "{{ instance_manifest.api_version | d('v1') }}"
kind: "{{ instance_manifest.kind | d('pg_spot_operator_instance') }}"
instance_name: "{{ instance_manifest.instance_name | d(engine_overrides.instance_name) }}"
description: "{{ instance_manifest.description | d('') }}"
cloud: "{{ instance_manifest.cloud | d('vagrant-libvirt') }}"
region: "{{ instance_manifest.region | d('local') }}"
is_paused: "{{ instance_manifest.is_paused | d(False) }}"
user_tags: "{{ instance_manifest.user_tags | d({}) | ansible.builtin.combine(engine_overrides.user_tags | d({})) }}"
setup_finished_callback: "{{ instance_manifest.setup_finished_callback | engine_overrides.setup_finished_callback | d('') }}"

connstr_private: "{{ engine_overrides.connstr_private | d('') }}"
connstr_public: "{{ engine_overrides.connstr_public | d('') }}"

# Apply override manifest sections if any
postgresql: "{{ default_manifest.postgresql | d({})
            | ansible.builtin.combine(instance_manifest.postgresql | d({}), recursive=true)
            | ansible.builtin.combine(engine_overrides.postgresql | d({}), recursive=true) }}"
vm: "{{ default_manifest.vm | d({})
    | ansible.builtin.combine(instance_manifest.vm | d({}), recursive=true)
    | ansible.builtin.combine(engine_overrides.vm | d({}), recursive=true) }}"
os: "{{ default_manifest.os | d({})
    | ansible.builtin.combine(instance_manifest.os | d({}), recursive=true)
    | ansible.builtin.combine(engine_overrides.os | d({}), recursive=true) }}"
backup: "{{ default_manifest.backup | d({})
    | ansible.builtin.combine(instance_manifest.backup | d({}), recursive=true)
    | ansible.builtin.combine(engine_overrides.backup | d({}), recursive=true) }}"
aws: "{{ default_manifest.aws | d({})
    | ansible.builtin.combine(instance_manifest.aws | d({}), recursive=true)
    | ansible.builtin.combine(engine_overrides.aws | d({}), recursive=true) }}"


postgres_cluster_name: "{{ instance_name | d('') | replace('-', '_') }}" # Dashes don't work with pg_createcluster"
