---
- block:

  - name: Install prometheus
    ansible.builtin.include_role:
      name: prometheus.prometheus.prometheus
    vars:
      prometheus_version: 2.54.1
      prometheus_web_listen_address: "{{ 'localhost:9090' if monitoring.prometheus_node_exporter.local_only|d(True) else '0.0.0.0:9090'  }}"

  - name: Install the node exporter
    ansible.builtin.include_role:
      name: prometheus.prometheus.node_exporter
    vars:
      node_exporter_version: 1.8.2
      node_exporter_web_listen_address: "{{ 'localhost:9100' if monitoring.prometheus_node_exporter.local_only|d(True) else '0.0.0.0:9100'  }}"
      node_exporter_web_disable_exporter_metrics: true
      # Description of collectors: https://github.com/prometheus/node_exporter?tab=readme-ov-file#node-exporter
      node_exporter_enabled_collectors:
        - disable-defaults
        - cpu
        - cpufreq
        - diskstats
        - filesystem
        - loadavg
        - meminfo
        - netdev
        - pressure
        - schedstat
        - stat
        - time

  when: monitoring.prometheus_node_exporter.enabled | d(False)

- block:

  # Following pretty much Grafana OSS Stable instructions from
  # https://grafana.com/docs/grafana/latest/setup-grafana/installation/debian/
  - name: Install the prerequisite packages
    ansible.builtin.apt:
      name: "{{ item }}"
      state: present
      update_cache: no
    loop:
      - apt-transport-https
      - software-properties-common
      - wget

  - name: Import the GPG key
    ansible.builtin.get_url:
      url: https://apt.grafana.com/gpg.key
      dest: /etc/apt/trusted.gpg.d/grafana.asc

  - name: Add the repository for stable releases
    ansible.builtin.apt_repository:
      repo: "deb [signed-by=/etc/apt/trusted.gpg.d/grafana.asc] https://apt.grafana.com stable main"
      filename: grafana
      state: present

  - name: Install Grafana
    ansible.builtin.apt:
      name: grafana
      state: present

  - name: Create a default prometheus datasource
    ansible.builtin.copy:
      src: files/prom_datasource.yml
      dest: /etc/grafana/provisioning/datasources/node_exporter.yaml
      owner: grafana

  - name: Generate grafana.ini
    ansible.builtin.template:
      src: grafana.ini
      dest: /etc/grafana/grafana.ini

  - name: Ensure Grafana started
    ansible.builtin.service: name=grafana-server state=started

  when: monitoring.grafana.enabled | d(False)
