---
- block:

  - name: Install prometheus
    ansible.builtin.include_role:
      name: prometheus.prometheus.prometheus
    vars:
      prometheus_version: 2.54.1
      prometheus_web_listen_address: localhost:9090

  - name: Install the node exporter
    ansible.builtin.include_role:
      name: prometheus.prometheus.node_exporter
    vars:
      node_exporter_version: 1.8.2
      node_exporter_web_listen_address: localhost:9100
      node_exporter_web_disable_exporter_metrics: true
      # Description of collectors: https://github.com/prometheus/node_exporter?tab=readme-ov-file#node-exporter
      node_exporter_enabled_collectors:
        - disable-defaults
        - cpu
        - cpufreq
        - diskstats
        - filesystem
        - loadavg
        - meminfo
        - netdev
        - pressure
        - schedstat
        - stat
        - time

  when: monitoring.node_exporter | d(False)
