---

- name: Merge Variables
  ansible.builtin.import_playbook: merge_vars.yml

- hosts: all
  become: true
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true

  roles:
    - role: configure_pgbackrest
