---

- name: Merge Variables
  ansible.builtin.import_playbook: _preprocess.yml

- hosts: all
  become: yes
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true

  roles:
    - role: mount_unattached_disks
    - role: install_os_pg_prereqs
    - role: init_pg_instance
