---
- hosts: all
  become: no
  any_errors_fatal: true
  # some merged vars may make use of server facts
  gather_facts: yes

  pre_tasks:
    - name: Include instance manifest
      ansible.builtin.include_vars:
        file: "vars/instance_manifest.yml"
        name: instance_manifest
    - name: Include engine override vars if any
      ansible.builtin.include_vars:
        file: "vars/engine_overrides.yml"
        name: engine_overrides

  roles:
    - role: merge_vars
