---
- hosts: all
  become: yes
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true

  pre_tasks:
    - name: Include instance manifest
      ansible.builtin.include_vars:
        file: "vars/instance_manifest.yml"
        name: instance_manifest
    - name: Include engine override vars if any
      ansible.builtin.include_vars:
        file: "vars/engine_overrides.yml"
        name: engine_overrides

  roles:
    - role: merge_vars
    - role: self_termination_setup
